### ISSUE TITLE
Suggestion for plugin

### ISSUE THREAD

**Issue by dot-bob** [OctoPrint/OctoPrint-MalyanConnectionFix#1]
Have you tried asserting RTS?  It seems the firmware on the mini delta I have is looking for CTS to be asserted before the will send data to the host.

**Comment by foosel** [comment]
I don't have access to this printer (or any model that would require this plugin) myself. All I had for even building this to go on were `serial.log`s from owners of affected models. And they claimed this is what works for them, also on a Mini Delta. Do I understand you correctly that you are still having issues in the current iteration? 

A couple months back I wrote an experimental plugin that didn't do the serial double open hack that this one here does but instead merely enabled rtscts after a user said they had read that somewhere. However, when people tested with that it did pretty much nothing at all.

Might also be due to some bug in pyserial however with the rtscts implementation, I see a couple of reports on that matter around as well.

**Comment by dot-bob** [comment]
I haven't tried the mini delta on OctoPrint for a while so I am not sure how it is working.  I have many other printers I prefer more so it doesn't see much use.  When I first received the mini delta I was having connection issues on my Windows box with any programs that didn't assert RTS.  I thought it was pretty odd that they required hardware handshaking as the port is simulated with the CDC class via USB directly to the micro.  I ended up writing a virtual com port application that the non compliant windows program would connect to and it would buffer / pass through comms to the mini delta port asserting RTS.  I thought about doing the same thing for the PI but never got around to it before I lost interest.
